baseURL = 'https://bitcommit.alumniei.pt/'
languageCode = 'pt-pt'
title = 'BitCommit 2026'

[params]
  description = 'BitCommit é um evento de tecnologia focado em palestras e workshops onde os participantes entram em contacto com diversas tecnologias e conceitos, focando-se nas skills técnicas e no contacto com empresas de topo a nível nacional e internacional.'
  event_date_display = '10 Outubro 2026'
  event_time = '14:30'
  location_venue = 'Founders Founders'
  location_city = 'Porto'
  location_address = 'R. da Constituição 346, 4200-192 Porto'
  tickets_url = 'https://bitcommit.alumniei.pt/'
  email = 'geral@alumniei.pt'
  copyright_year = '2026'
