baseURL = 'https://bitcommit.alumniei.pt/'
languageCode = 'pt-pt'
title = 'BitCommit 2026'
disableKinds = ['taxonomy', 'term']

[params]
  description = 'A BitCommit é uma mini-conferência, destinada a profissionais da área da informática, que tem o intuito de discutir IA na perspetiva de como nos afeta na vida profissional, em áreas como empregabilidade, saúde mental, aprendizagem e muitas outras. Neste evento, queremos desviar-nos da parte técnica e focar naquilo que consideramos mais importante: as pessoas! Por isso, a AlumniEI (Associação de Antigos Alunos de Engenharia Informática da FEUP) preparou este evento para criar um espaço para se discutir os desafios que enfrentamos nestas áreas e como podemos superá-los.'
  event_date_display = '10 Outubro 2026'
  event_time = '14:30'
  location_venue = 'Founders Founders'
  location_city = 'Porto'
  location_address = 'Rua de Godim 389, 4300-240 Porto'
  location_maps_url = 'https://maps.app.goo.gl/bKAY6yicGjBpS5H96'
  tickets_url = 'https://www.eventbrite.com/e/bilhetes-bitcommit-2001083276949?aff=oddtdtcreator'
  tickets_button_text = 'Garante já o teu bilhete'
  email = 'geral@alumniei.pt'
  copyright_year = '2026'
  enable_sponsors = false
  enable_speakers = true
  enable_directions = true
